### ISSUE TITLE
수정

### ISSUE THREAD

**Issue by tmdwls1** [tmdwls1/CRUD-board#7]

**Comment by rttteees** [comment]
663fa2e1cc0ccb901389c5a902ca7c45f058ddb9
게시판 리스트 수정 
-> 가운데 정렬

**Comment by rttteees** [comment]
글 작성 버튼  추가
7391329332808e4e8b4e23a405bcbe94da1050b5

**Comment by rttteees** [comment]
342e6bfcae71c96a2c09935fa4098effa76a87b7
글 화면 html 수정
